# Generated by Django 5.2 on 2025-04-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio_files',
            new_name='audio_file',
        ),
    ]
