# Generated by Django 5.1.7 on 2026-03-10 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Music_app", "0003_alter_song_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="media/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
