# Generated by Django 5.1.7 on 2026-03-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Music_app", "0004_alter_song_audio_file_alter_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
